name: self hosted runner workflow

on:
  push:
    branches: 
      - master

jobs:
    -name: print stage
      runs-on: self-hosted
    steps :
        - name: checkout repository
          uses: actions/checkout@v3
        - name: printing stage  
          run: echo "this job is running on self-hosted runner"
