name: self hosted runner workflow

on:
  workflow_dispatch

jobs:
    print-stage:
      runs-on: self-hosted
      steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: printing stage  
        run: echo "this job is running on self-hosted runner"
      - name: Group loggin
        run: |
          echo "::group::My Group messages"  
          echo "msg1"
          echo "msg2"
          echo "::endgroup::"
